name: AAA

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  reveal-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print Secrets with Spaces
        run: |
          echo "KEYSTORE_PASSWORD=$(echo '${{ secrets.KEYSTORE_PASSWORD }}' | sed 's/./& /g')"
          echo "KEY_ALIAS=$(echo '${{ secrets.KEY_ALIAS }}' | sed 's/./& /g')"
          echo "KEY_PASSWORD=$(echo '${{ secrets.KEY_PASSWORD }}' | sed 's/./& /g')"

